export interface Product {
  id: string
  name: string
  description: string
  price: number
  category: string[]
  weather: string[]
  activities: string[]
  image: string
}

export const products: Product[] = [
  {
    id: "sleeping-bag-winter",
    name: "Alpine Winter Sleeping Bag",
    description: "Rated for temperatures down to -20°F, perfect for tall individuals up to 6'6\"",
    price: 299.99,
    category: ["sleeping", "winter-gear"],
    weather: ["cold", "extreme-cold"],
    activities: ["camping", "mountaineering"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "tent-tall",
    name: "Wilderness Extended Height Tent",
    description: "3-season tent with 7' center height, ideal for tall campers",
    price: 449.99,
    category: ["shelter", "tents"],
    weather: ["mild", "cold", "rain"],
    activities: ["camping", "backpacking"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "insulated-jacket",
    name: "Mountain Pro Insulated Jacket",
    description: "Tall sizes available, waterproof and breathable winter jacket",
    price: 299.99,
    category: ["clothing", "winter-gear"],
    weather: ["cold", "extreme-cold", "wind", "rain"],
    activities: ["hiking", "camping", "mountaineering"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "hiking-boots",
    name: "All-Terrain Hiking Boots",
    description: "Waterproof hiking boots with excellent ankle support, available in extended sizes",
    price: 189.99,
    category: ["footwear"],
    weather: ["all-weather"],
    activities: ["hiking", "backpacking", "mountaineering"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "climbing-shoes",
    name: "Rock Climbing Shoes",
    description: "Top of the line climbing shoes. Climb harder and longer, suffer less, available in extended sizes",
    price: 89.99,
    category: ["footwear", "rock climbing"],
    weather: ["all-weather"],
    activities: ["climbing", "rock climbing", "mountaineering"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "climbing-harness",
    name: "Rock Climbing Harness",
    description: "Gear you can trust. All you need for gym and crag climbing, and it's built in an environmentally friendly way.",
    price: 69.99,
    category: ["rock climbing"],
    weather: ["all-weather"],
    activities: ["rock climbing", "mountaineering"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "backpack-65l",
    name: "Expedition 65L Backpack",
    description: "Large capacity backpack with adjustable torso length for tall hikers",
    price: 279.99,
    category: ["bags", "backpacks"],
    weather: ["all-weather"],
    activities: ["hiking", "backpacking", "camping"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "trekking-poles",
    name: "Carbon Fiber Trekking Poles",
    description: "Adjustable length trekking poles with cork grips",
    price: 129.99,
    category: ["accessories"],
    weather: ["all-weather"],
    activities: ["hiking", "backpacking", "mountaineering"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "camp-stove",
    name: "Ultralight Camp Stove",
    description: "Compact and efficient camp stove for backcountry cooking",
    price: 69.99,
    category: ["cooking", "camp-kitchen"],
    weather: ["all-weather"],
    activities: ["camping", "backpacking"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "water-filter",
    name: "Advanced Water Filtration System",
    description: "Removes 99.99999% of waterborne bacteria and protozoa",
    price: 39.99,
    category: ["water", "safety"],
    weather: ["all-weather"],
    activities: ["camping", "hiking", "backpacking"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "down-jacket",
    name: "Ultralight Down Jacket",
    description: "800-fill power down jacket, packs into its own pocket",
    price: 249.99,
    category: ["clothing", "winter-gear"],
    weather: ["cold", "mild"],
    activities: ["hiking", "camping", "casual"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "rain-shell",
    name: "Lightweight Rain Shell",
    description: "Waterproof and breathable rain jacket with pit zips",
    price: 169.99,
    category: ["clothing", "rain-gear"],
    weather: ["rain", "wind"],
    activities: ["hiking", "camping", "casual"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "hiking-pants",
    name: "Convertible Hiking Pants",
    description: "Quick-dry convertible pants with UPF 50+ protection",
    price: 89.99,
    category: ["clothing"],
    weather: ["mild", "warm"],
    activities: ["hiking", "camping", "casual"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "headlamp",
    name: "Rechargeable Headlamp",
    description: "350 lumens LED headlamp with red night vision mode",
    price: 49.99,
    category: ["accessories", "lighting"],
    weather: ["all-weather"],
    activities: ["camping", "hiking", "emergency"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "bear-canister",
    name: "Bear-Resistant Food Container",
    description: "Required for many wilderness areas, protects your food from wildlife",
    price: 79.99,
    category: ["food-storage", "safety"],
    weather: ["all-weather"],
    activities: ["camping", "backpacking"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "sleeping-pad",
    name: "Insulated Sleeping Pad",
    description: "4-season sleeping pad with R-value of 6.9",
    price: 179.99,
    category: ["sleeping"],
    weather: ["all-weather", "cold"],
    activities: ["camping", "backpacking"],
    image: "/placeholder.svg?height=300&width=300",
  },
  {
    id: "camp-chair",
    name: "Packable Camp Chair",
    description: "Comfortable and lightweight, supports up to 300 lbs",
    price: 99.99,
    category: ["furniture", "comfort"],
    weather: ["all-weather"],
    activities: ["camping", "outdoor-events"],
    image: "/placeholder.svg?height=300&width=300",
  },
]

