export interface Product {
  id: string
  name: string
  description: string
  price: number
  category: string[]
  weather: string[]
  activities: string[]
  image: string
}

export const products: Product[] = [
  {
    id: "sleeping-bag-winter",
    name: "Alpine Winter Sleeping Bag",
    description: "Rated for temperatures down to -20°F, perfect for tall individuals up to 6'6\"",
    price: 299.99,
    category: ["sleeping", "winter-gear"],
    weather: ["cold", "extreme-cold"],
    activities: ["camping", "mountaineering"],
    image: "https://www.militarykit.com/cdn/shop/products/snugpak-navigator-sleeping-bag-olive_grande.jpg?v=1581436850",
  },
  {
    id: "tent-tall",
    name: "Wilderness Extended Height Tent",
    description: "3-season tent with 7' center height, ideal for tall campers",
    price: 449.99,
    category: ["shelter", "tents"],
    weather: ["mild", "cold", "rain"],
    activities: ["camping", "backpacking"],
    image: "https://www.bigagnes.com/cdn/shop/files/Blacktail-3-Hotel-01_600x.png?v=1734723376",
  },
  {
    id: "insulated-jacket",
    name: "Mountain Pro Insulated Jacket",
    description: "Tall sizes available, waterproof and breathable winter jacket",
    price: 299.99,
    category: ["clothing", "winter-gear"],
    weather: ["cold", "extreme-cold", "wind", "rain"],
    activities: ["hiking", "camping", "mountaineering"],
    image: "https://cdn11.bigcommerce.com/s-nea9lcsxle/images/stencil/1280x1280/products/14831/19037/bc636764Screenshot%202023-10-03%20103226__07751.1696343591.png?c=1",
  },
  {
    id: "hiking-boots",
    name: "All-Terrain Hiking Boots",
    description: "Waterproof hiking boots with excellent ankle support, available in extended sizes",
    price: 189.99,
    category: ["footwear"],
    weather: ["all-weather"],
    activities: ["hiking", "backpacking", "mountaineering"],
    image: "https://meindlusa.com/cdn/shop/files/LadyKansas_Main_10920f4b-b36d-4383-aa45-3604fafe0c5f_1024x.png?v=1715187719",
  },
  {
    id: "climbing-shoes",
    name: "Rock Climbing Shoes",
    description: "Top of the line climbing shoes. Climb harder and longer, suffer less, available in extended sizes",
    price: 89.99,
    category: ["footwear", "rock climbing"],
    weather: ["all-weather"],
    activities: ["climbing", "rock climbing", "mountaineering"],
    image: "https://lcdn.lasportivausa.com/pub/media/catalog/product/z/f/zfcs005_k00y00_skwama_blackyellow_3_4.jpg?width=700&height=700&store=en&image-type=image",
  },
  {
    id: "climbing-harness",
    name: "Rock Climbing Harness",
    description: "Gear you can trust. All you need for gym and crag climbing, and it's built in an environmentally friendly way.",
    price: 69.99,
    category: ["rock climbing"],
    weather: ["all-weather"],
    activities: ["rock climbing", "mountaineering"],
    image: "https://m.media-amazon.com/images/I/71jGNwa-TiL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: "backpack-65l",
    name: "Expedition 65L Backpack",
    description: "Large capacity backpack with adjustable torso length for tall hikers",
    price: 279.99,
    category: ["bags", "backpacks"],
    weather: ["all-weather"],
    activities: ["hiking", "backpacking", "camping"],
    image: "https://cdni.llbean.net/is/image/wim/520605_53152_44?hei=1095&wid=950&resMode=sharp2&defaultImage=llbprod/520605_53152_41",
  },
  {
    id: "trekking-poles",
    name: "Carbon Fiber Trekking Poles",
    description: "Adjustable length trekking poles with cork grips",
    price: 129.99,
    category: ["accessories"],
    weather: ["all-weather"],
    activities: ["hiking", "backpacking", "mountaineering"],
    image: "https://cdn11.bigcommerce.com/s-hgn1l9sh63/product_images/attribute_rule_images/22705_source_1706770861.jpg",
  },
  {
    id: "camp-stove",
    name: "Ultralight Camp Stove",
    description: "Compact and efficient camp stove for backcountry cooking",
    price: 69.99,
    category: ["cooking", "camp-kitchen"],
    weather: ["all-weather"],
    activities: ["camping", "backpacking"],
    image: "https://gofsr.com/cdn/shop/files/PortableCampStove_WhiteCyc-32.jpg?v=1723055456&width=3000",
  },
  {
    id: "water-filter",
    name: "Advanced Water Filtration System",
    description: "Removes 99.99999% of waterborne bacteria and protozoa",
    price: 39.99,
    category: ["water", "safety"],
    weather: ["all-weather"],
    activities: ["camping", "hiking", "backpacking"],
    image: "https://www.aosmithatlowes.com/media/1104/ao-mf-adv-main.png",
  },
  {
    id: "down-jacket",
    name: "Ultralight Down Jacket",
    description: "800-fill power down jacket, packs into its own pocket",
    price: 249.99,
    category: ["clothing", "winter-gear"],
    weather: ["cold", "mild"],
    activities: ["hiking", "camping", "casual"],
    image: "https://www.logowearplus.com/v/vspfiles/photos/84757-2T.jpg",
  },
  {
    id: "rain-shell",
    name: "Lightweight Rain Shell",
    description: "Waterproof and breathable rain jacket with pit zips",
    price: 169.99,
    category: ["clothing", "rain-gear"],
    weather: ["rain", "wind"],
    activities: ["hiking", "camping", "casual"],
    image: "https://www.adventurealan.com/wp-content/uploads/2021/03/Enlightened-Equipment-Visp-Rain-Jacket.jpg",
  },
  {
    id: "hiking-pants",
    name: "Convertible Hiking Pants",
    description: "Quick-dry convertible pants with UPF 50+ protection",
    price: 89.99,
    category: ["clothing"],
    weather: ["mild", "warm"],
    activities: ["hiking", "camping", "casual"],
    image: "https://www.adventurealan.com/wp-content/uploads/2021/04/REI-Co-op-Sahara-convertible-Pants.jpg",
  },
  {
    id: "headlamp",
    name: "Rechargeable Headlamp",
    description: "350 lumens LED headlamp with red night vision mode",
    price: 49.99,
    category: ["accessories", "lighting"],
    weather: ["all-weather"],
    activities: ["camping", "hiking", "emergency"],
    image: "https://policesecurity.com/cdn/shop/files/98730-BLACKOUT-R-HERO-SHADOW_1200x.jpg?v=1738787613",
  },
  {
    id: "bear-canister",
    name: "Bear-Resistant Food Container",
    description: "Required for many wilderness areas, protects your food from wildlife",
    price: 79.99,
    category: ["food-storage", "safety"],
    weather: ["all-weather"],
    activities: ["camping", "backpacking"],
    image: "https://m.media-amazon.com/images/I/81g0EfnvsVL.jpg",
  },
  {
    id: "sleeping-pad",
    name: "Insulated Sleeping Pad",
    description: "4-season sleeping pad with R-value of 6.9",
    price: 179.99,
    category: ["sleeping"],
    weather: ["all-weather", "cold"],
    activities: ["camping", "backpacking"],
    image: "https://whaletalesarchery.com/wp-content/uploads/2022/06/Klymit_InsulatedStaticV_06IVOR01C_AngleBag_v1_2000x2000_99bd02f2-bfc9-4199-bc9e-6123eb0b33a9_5000x.webp",
  },
  {
    id: "camp-chair",
    name: "Packable Camp Chair",
    description: "Comfortable and lightweight, supports up to 300 lbs",
    price: 99.99,
    category: ["furniture", "comfort"],
    weather: ["all-weather"],
    activities: ["camping", "outdoor-events"],
    image: "https://cascademountaintech.com/cdn/shop/products/HBS-GR-21200x1200.jpg?v=1653559369",
  },
  {
    id: "hiking-socks-merino",
    name: "Merino Wool Hiking Socks",
    description: "Moisture-wicking, odor-resistant wool socks for long hikes",
    price: 24.99,
    category: ["clothing", "footwear"],
    weather: ["cold", "mild"],
    activities: ["hiking", "camping", "backpacking"],
    image: "https://www.gowithsocks.com/cdn/shop/files/merino-wool-hiking-socks-green-2-pairs.webp?v=1704644326",
  },
  {
    id: "thermal-socks",
    name: "Extreme Cold Thermal Socks",
    description: "Designed for freezing temperatures, extra thick and warm",
    price: 29.99,
    category: ["clothing", "winter-gear"],
    weather: ["cold", "extreme-cold"],
    activities: ["camping", "mountaineering"],
    image: "https://cdn11.bigcommerce.com/s-skjz97mme0/images/stencil/500x659/products/122/662/Blue-Flame-E-Tech-Bamboo-Thermal-Socks-Group__05880.1605762174.jpg?c=2",
  },
  {
    id: "base-layer-top",
    name: "Moisture-Wicking Base Layer Top",
    description: "Breathable and quick-drying base layer for active wear",
    price: 59.99,
    category: ["clothing"],
    weather: ["all-weather"],
    activities: ["hiking", "camping", "mountaineering"],
    image: "https://www.rei.com/media/993d8470-f5f7-416d-b79a-537a50d910d5.jpg",
  },
  {
    id: "flannel-shirt",
    name: "Heavy-Duty Outdoor Flannel",
    description: "Durable, warm, and stylish flannel shirt for outdoor adventures",
    price: 69.99,
    category: ["clothing"],
    weather: ["mild", "cold"],
    activities: ["camping", "casual"],
    image: "https://cdn11.bigcommerce.com/s-20kzykhhd5/images/stencil/1280x1280/products/3319/14726/WS04-RDPL_front__98832.1736891488.jpg?c=2",
  },
  {
    id: "softshell-pants",
    name: "Softshell Hiking Pants",
    description: "Wind and water-resistant pants for tough conditions",
    price: 119.99,
    category: ["clothing"],
    weather: ["cold", "wind"],
    activities: ["hiking", "mountaineering"],
    image: "https://www.snowpeak.com/cdn/shop/products/PA-24SU006_Slateblue_P_01_png.png?v=1709154872",
  },
  {
    id: "thermal-leggings",
    name: "Thermal Leggings",
    description: "Insulated leggings for extra warmth in winter conditions",
    price: 79.99,
    category: ["clothing", "winter-gear"],
    weather: ["cold"],
    activities: ["camping", "skiing"],
    image: "https://cdn11.bigcommerce.com/s-r4f6haoaux/images/stencil/1280x1280/products/167/684/mens-heavyweight-thermal-bottom-long-underwear-natural-Polar-King-173-10-front__56263.1582847657.jpg?c=1",
  },
  {
    id: "hiking-shorts",
    name: "Trail-Ready Hiking Shorts",
    description: "Lightweight and breathable shorts with multiple pockets",
    price: 54.99,
    category: ["clothing"],
    weather: ["warm"],
    activities: ["hiking", "camping"],
    image: "https://www.rei.com/media/product/2426450017",
  },
  {
    id: "winter-gloves",
    name: "Extreme Cold Winter Gloves",
    description: "Waterproof, insulated gloves for sub-zero temperatures",
    price: 89.99,
    category: ["clothing", "winter-gear"],
    weather: ["cold", "extreme-cold"],
    activities: ["camping", "mountaineering"],
    image: "https://www.westmarine.com/on/demandware.static/-/Sites-wm-master-catalog/default/dw73efd5eb/images/orig/P019634344_BLACK_1500.19072019023109.jpg",
  },
  {
    id: "lightweight-gloves",
    name: "Lightweight Trail Gloves",
    description: "Flexible and breathable gloves for mild weather",
    price: 34.99,
    category: ["clothing"],
    weather: ["mild"],
    activities: ["hiking", "trail running"],
    image: "https://www.giro.com/dw/image/v2/BDBJ_PRD/on/demandware.static/-/Sites-giro-master-catalog/default/dwed386bb0/images/large/giro-xnetic-trail-dirt-gloves-coal-hero.jpg?sw=800&sh=800&sm=fit",
  },
  {
    id: "beanie",
    name: "Merino Wool Beanie",
    description: "Warm and breathable, fits under helmets",
    price: 29.99,
    category: ["clothing"],
    weather: ["cold"],
    activities: ["camping", "hiking"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbCO_ubtdyNBRl2-mHqYbWqJF-glMN7nAhKQ&s",
  },
  {
    id: "sun-hat",
    name: "Wide-Brim Sun Hat",
    description: "UPF 50+ protection, moisture-wicking sweatband",
    price: 39.99,
    category: ["clothing"],
    weather: ["warm"],
    activities: ["hiking", "camping"],
    image: "https://setartrading.com/cdn/shop/products/hh1009_sahara_large_brim_sun_hat_with_chin_cord_for_women_natural.jpg?v=1623037559",
  },
  {
    id: "high-end-sleeping-bag",
    name: "Expedition Down Sleeping Bag",
    description: "Rated for -40°F, ultralight and highly compressible",
    price: 799.99,
    category: ["sleeping", "winter-gear"],
    weather: ["extreme-cold"],
    activities: ["mountaineering", "arctic expeditions"],
    image: "https://target.scene7.com/is/image/Target/GUEST_50dba949-9f36-427f-86d6-a895c2143fe3",
  },
  {
    id: "gps-watch",
    name: "Adventure GPS Smartwatch",
    description: "Track routes, monitor altitude, and measure heart rate",
    price: 499.99,
    category: ["electronics", "accessories"],
    weather: ["all-weather"],
    activities: ["hiking", "mountaineering", "running", "camping"],
    image: "https://i5.walmartimages.com/seo/SUUNTO-Vertical-Adventure-GPS-Watch-Large-Screen-Offline-Maps-Solar-Charging_1fecd67b-c9a7-4d87-87fe-9c3464a483c7.74960aebd539d88c5f57594f9a6ef1f9.jpeg",
  },
  {
    id: "basic-camping-mug",
    name: "Stainless Steel Camping Mug",
    description: "Durable and lightweight, perfect for coffee by the campfire",
    price: 9.99,
    category: ["camp-kitchen"],
    weather: ["all-weather"],
    activities: ["camping", "backpacking"],
    image: "https://i5.walmartimages.com/seo/Camping-Cup-Camping-Mug-with-Foldable-Handles-Stainless-Steel-Drinkware-Camping-Water-Boiling-Cup-Outdoor-Cups-for-Backpacking-Outdoor-260ml_8506bd81-f8e6-4ec3-82ab-e8be8945a961.25a3498a8c57bea75d3323015acf80c4.jpeg",
  },
  {
    id: "budget-rain-jacket",
    name: "Waterproof Rain Jacket Shell",
    description: "Affordable rain protection, lightweight and packable",
    price: 49.99,
    category: ["clothing", "rain-gear"],
    weather: ["rain", "wind"],
    activities: ["hiking", "casual"],
    image: "https://m.media-amazon.com/images/I/71Db5BQOtjL._AC_UY1000_.jpg",
  },
  {
    id: "cheap-camping-chair",
    name: "Basic Folding Camping Chair",
    description: "Lightweight and easy to pack, great for quick trips",
    price: 39.99,
    category: ["furniture", "comfort"],
    weather: ["all-weather"],
    activities: ["camping", "outdoor-events"],
    image: "https://images.thdstatic.com/productImages/337c2a48-627c-4c01-acb7-330172b1bde2/svn/blue-camping-chairs-thd-e01cc401-blue-64_300.jpg",
  },
  {
    id: "bike-helmet-pro",
    name: "Pro Cycling Helmet",
    description: "Lightweight, aerodynamic helmet with advanced ventilation and MIPS safety system.",
    price: 149.99,
    category: ["biking", "safety"],
    weather: ["all-weather"],
    activities: ["cycling", "mountain biking"],
    image: "https://classiccycling.com/cdn/shop/products/limar-air-pro-cycling-helmet-721396_700x.jpg?v=1647046837",
  },
  {
    id: "mtb-full-face-helmet",
    name: "Full-Face MTB Helmet",
    description: "Downhill mountain biking helmet with extended protection and impact resistance.",
    price: 199.99,
    category: ["biking", "safety"],
    weather: ["all-weather"],
    activities: ["mountain biking"],
    image: "https://m.media-amazon.com/images/I/51HtDmUxC-L.jpg",
  },
  {
    id: "cycling-gloves-summer",
    name: "Breathable Cycling Gloves",
    description: "Fingerless padded gloves for long rides with excellent grip.",
    price: 29.99,
    category: ["biking", "clothing"],
    weather: ["mild", "warm"],
    activities: ["cycling"],
    image: "https://www.cycleafer.com/cdn/shop/products/51Zk3M4RcnL.jpg?v=1672872961",
  },
  {
    id: "cycling-gloves-winter",
    name: "Winter Cycling Gloves",
    description: "Windproof and waterproof gloves with touchscreen compatibility.",
    price: 49.99,
    category: ["biking", "clothing", "winter-gear"],
    weather: ["cold", "wind"],
    activities: ["cycling", "mountain biking"],
    image: "https://www.montonsports.com/media/catalog/product/cache/2a4ba1415b5422d0df23fdfdde95fd92/0/1/01_108_3.jpg",
  },
  {
    id: "cycling-bib-shorts",
    name: "Cycling Bib Shorts",
    description: "Padded, moisture-wicking bib shorts for maximum comfort on long rides.",
    price: 89.99,
    category: ["biking", "clothing"],
    weather: ["warm"],
    activities: ["cycling"],
    image: "https://img.santinicycling.com/us/154211-large_default/rx-bib-shorts.jpg",
  },
  {
    id: "mountain-bike-shorts",
    name: "Mountain Biking Shorts",
    description: "Durable and flexible MTB shorts with multiple pockets.",
    price: 74.99,
    category: ["biking", "clothing"],
    weather: ["mild", "warm"],
    activities: ["mountain biking"],
    image: "https://cycorldpro.com/cdn/shop/products/10_6378044d-3f30-465b-921c-edea68f9dfc0.jpg?v=1645079285",
  },
  {
    id: "cycling-shoes-road",
    name: "Road Cycling Shoes",
    description: "Stiff carbon sole and BOA closure for optimal pedaling efficiency.",
    price: 199.99,
    category: ["biking", "footwear"],
    weather: ["all-weather"],
    activities: ["cycling"],
    image: "https://www.giro.com/on/demandware.static/-/Sites-giro-master-catalog/default/dw0a727920/images/large/giro-cadet-road-shoe-ano-blue-profile.jpg",
  },
  {
    id: "cycling-shoes-mtb",
    name: "Mountain Biking Shoes",
    description: "Grippy soles and SPD compatibility for trail riding.",
    price: 149.99,
    category: ["biking", "footwear"],
    weather: ["all-weather"],
    activities: ["mountain biking"],
    image: "https://www.giro.com/dw/image/v2/BDBJ_PRD/on/demandware.static/-/Sites-giro-master-catalog/default/dw76432bb2/images/large/giro-gauge-dirt-shoe-trail-green-spectra-yellow-profile.jpg?sw=800&sh=800&sm=fit",
  },
  {
    id: "cycling-windbreaker",
    name: "Packable Cycling Windbreaker",
    description: "Ultralight, windproof jacket that fits into a jersey pocket.",
    price: 79.99,
    category: ["biking", "clothing"],
    weather: ["wind", "mild"],
    activities: ["cycling"],
    image: "https://cdn11.bigcommerce.com/s-cmcj94sbu5/images/stencil/800x800/products/4045/18316/Lightweight_Packable_RainJacket_Safety_OffFront_Full__73219.1683045768.jpg?c=2",
  },
  {
    id: "cycling-rain-jacket",
    name: "Waterproof Cycling Jacket",
    description: "Breathable and waterproof shell with reflective details.",
    price: 129.99,
    category: ["biking", "clothing", "rain-gear"],
    weather: ["rain", "wind"],
    activities: ["cycling"],
    image: "https://showerspass.com/cdn/shop/files/MensEliteIII_3_4_WEB.jpg?v=1728765385",
  },
  {
    id: "bike-light-front",
    name: "High-Lumen Bike Headlight",
    description: "Rechargeable front light with 1200 lumens for night rides.",
    price: 59.99,
    category: ["biking", "electronics"],
    weather: ["all-weather"],
    activities: ["cycling", "mountain biking"],
    image: "https://cdn11.bigcommerce.com/s-i3pt5y1dai/images/stencil/1280x1280/products/592/2474/Planet_Bike_Beamer_200_bike_headlight_on_copy__38814.1705440722.jpg?c=1",
  },
  {
    id: "bike-light-rear",
    name: "USB Rechargeable Rear Bike Light",
    description: "Ultra-bright red LED with multiple flashing modes for safety.",
    price: 29.99,
    category: ["biking", "electronics"],
    weather: ["all-weather"],
    activities: ["cycling"],
    image: "https://www.statebicycle.com/cdn/shop/products/State-Bicycle-Co--USB-Rechargeable-LED-Bike-Light-rear-1_jpg_64a111a5-87b0-4a05-ba29-eb0dd08db36f.jpg?v=1684441760",
  },
  {
    id: "bike-pump",
    name: "Portable Bike Pump",
    description: "Lightweight, high-pressure pump for road and mountain bikes.",
    price: 34.99,
    category: ["biking", "accessories"],
    weather: ["all-weather"],
    activities: ["cycling", "mountain biking"],
    image: "https://s.alicdn.com/@sc04/kf/H929130ad71cd466089f58e8e444f7f8c5.jpg_720x720q50.jpg",
  },
  {
    id: "bike-repair-kit",
    name: "Complete Bike Repair Kit",
    description: "Includes multi-tool, tire levers, and patches for on-the-go fixes.",
    price: 44.99,
    category: ["biking", "accessories"],
    weather: ["all-weather"],
    activities: ["cycling", "mountain biking"],
    image: "https://m.media-amazon.com/images/I/71bzH7rtJ2L.jpg",
  },
  {
    id: "hydration-pack",
    name: "Cycling Hydration Pack",
    description: "Lightweight backpack with a 2L water reservoir for long rides.",
    price: 69.99,
    category: ["biking", "accessories"],
    weather: ["all-weather"],
    activities: ["cycling", "mountain biking"],
    image: "https://uswe.com/media/resized/489x489/uswe-rush-8-carbon-black-2085501m_001-min_5.jpg",
  },
  {
    id: "triathlon-wetsuit-mens",
    name: "Men's Triathlon Wetsuit",
    description: "Buoyancy-enhancing, flexible wetsuit designed for open water swimming.",
    price: 299.99,
    category: ["triathlon", "swimming"],
    weather: ["cold", "mild"],
    activities: ["triathlon", "swimming"],
    image: "https://www.orca.com/uploads/products/large/mn12tt43-01-orca-apex-flex-men-triathlon-wetsuit-blue-flex_750x1000.jpg",
  },
  {
    id: "triathlon-wetsuit-womens",
    name: "Women's Triathlon Wetsuit",
    description: "Streamlined, hydrodynamic wetsuit for faster swim times.",
    price: 299.99,
    category: ["triathlon", "swimming"],
    weather: ["cold", "mild"],
    activities: ["triathlon", "swimming"],
    image: "https://www.orca.com/uploads/products/large/mn12tt43-01-orca-apex-flex-men-triathlon-wetsuit-blue-flex_750x1000.jpg",
  },
  {
    id: "triathlon-bike",
    name: "Aero Triathlon Bike",
    description: "Lightweight carbon fiber frame with aero handlebars for maximum speed.",
    price: 2999.99,
    category: ["triathlon", "biking"],
    weather: ["all-weather"],
    activities: ["triathlon", "cycling"],
    image: "https://www.storck-bikes.com/images/categories/medium/aero3_12027.jpg",
  },
  {
    id: "clip-on-aero-bars",
    name: "Clip-On Aero Bars",
    description: "Transform your road bike into a triathlon-ready setup.",
    price: 129.99,
    category: ["triathlon", "biking"],
    weather: ["all-weather"],
    activities: ["triathlon", "cycling"],
    image: "https://redshiftsports.com/cdn/shop/products/PB180300_2_3612x.jpg?v=1619823766",
  },
  {
    id: "triathlon-running-shoes",
    name: "Triathlon Running Shoes",
    description: "Elastic laces and breathable design for quick transitions.",
    price: 159.99,
    category: ["triathlon", "running"],
    weather: ["all-weather"],
    activities: ["triathlon", "running"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR63UEiFADx-7VPbuclW7UX5bvTIACeYj0jmg&s",
  },
  {
    id: "triathlon-suit-mens",
    name: "Men's Triathlon Suit",
    description: "One-piece suit designed for swim, bike, and run transitions.",
    price: 149.99,
    category: ["triathlon", "clothing"],
    weather: ["warm"],
    activities: ["triathlon"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhJz5Chdcptopq-4FSbPI7qpHjSxrBzRjsKw&s",
  },
  {
    id: "triathlon-suit-womens",
    name: "Women's Triathlon Suit",
    description: "Quick-drying, compression-fit tri suit for endurance races.",
    price: 149.99,
    category: ["triathlon", "clothing"],
    weather: ["warm"],
    activities: ["triathlon"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhJz5Chdcptopq-4FSbPI7qpHjSxrBzRjsKw&s",
  },
  {
    id: "swim-goggles",
    name: "Anti-Fog Swim Goggles",
    description: "Polarized lenses for glare reduction in open water swimming.",
    price: 49.99,
    category: ["triathlon", "swimming"],
    weather: ["all-weather"],
    activities: ["triathlon", "swimming"],
    image: "https://outdoormaster.com/cdn/shop/files/GobyAnti-fogSwimGogglesAdultsMenWomenYouth-1.jpg?v=1711097719",
  },
  {
    id: "swim-buoy",
    name: "Open Water Swim Buoy",
    description: "High-visibility buoy for added safety in open water training.",
    price: 39.99,
    category: ["triathlon", "swimming"],
    weather: ["all-weather"],
    activities: ["triathlon", "swimming"],
    image: "https://elsmoreswim.com/cdn/shop/products/open-water-swim-buoy-med-15l-owsb-15l_pvc-yellow_1_dcdb3ff7-2028-4c64-bc2a-5be80ec0bae7.jpg?v=1682958591",
  },
  {
    id: "triathlon-water-bottle",
    name: "Triathlon Hydration Bottle",
    description: "Aerodynamic bottle for easy hydration on the bike leg.",
    price: 29.99,
    category: ["triathlon", "accessories"],
    weather: ["all-weather"],
    activities: ["triathlon", "cycling"],
    image: "https://arvadatri.com/cdn/shop/products/PFH-1L-1_ff20ca57-f940-412c-9bbe-28ced2b7b030.webp?v=1710010153",
  },
  {
    id: "energy-gels",
    name: "Endurance Energy Gels",
    description: "Fast-absorbing carbs and electrolytes for sustained energy.",
    price: 19.99,
    category: ["triathlon", "nutrition"],
    weather: ["all-weather"],
    activities: ["triathlon", "running", "cycling"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjaG79GgERAIY9iBw7TpGVdjG_tPEd2PDxow&s",
  },
  {
    id: "race-belt",
    name: "Triathlon Race Belt",
    description: "Quick-attach race number belt with gel loops.",
    price: 19.99,
    category: ["triathlon", "accessories"],
    weather: ["all-weather"],
    activities: ["triathlon"],
    image: "https://m.media-amazon.com/images/I/61GVWrhyGsL._AC_UY1000_.jpg",
  },
  {
    id: "transition-mat",
    name: "Triathlon Transition Mat",
    description: "Non-slip mat for fast and efficient transitions.",
    price: 39.99,
    category: ["triathlon", "accessories"],
    weather: ["all-weather"],
    activities: ["triathlon"],
    image: "https://m.media-amazon.com/images/I/51t5mauun1L._AC_SL1500_.jpg",
  },
  {
    id: "foam-roller",
    name: "Deep Tissue Foam Roller",
    description: "Speeds up muscle recovery and improves flexibility.",
    price: 34.99,
    category: ["triathlon", "recovery"],
    weather: ["all-weather"],
    activities: ["triathlon", "running", "cycling"],
    image: "https://teeter.com/wp-content/uploads/2022/02/02_Teeter-Massage-Roam-Roller_1120.jpg",
  },
  {
    id: "smart-trainer",
    name: "Indoor Smart Bike Trainer",
    description: "Realistic road feel and smart resistance control.",
    price: 899.99,
    category: ["triathlon", "biking", "training"],
    weather: ["indoor"],
    activities: ["triathlon", "cycling"],
    image: "https://us.zwift.com/cdn/shop/files/wahoo-kickr-bike-shift-smart-bike-trainer_2048x.jpg?v=1694107925",
  },
  {
    id: "running-shoes-road",
    name: "Road Running Shoes",
    description: "Lightweight, cushioned shoes designed for high-mileage road running.",
    price: 159.99,
    category: ["running", "footwear"],
    weather: ["all-weather"],
    activities: ["running", "training"],
    image: "https://assets.altrarunning.com/image/upload/f_auto,q_auto,dpr_auto/b_transparent,c_pad,ar_1.0,w_auto/w_740/d_noimage.png/AL0A85NV264-HERO?_i=AG",
  },
  {
    id: "running-shoes-trail",
    name: "Trail Running Shoes",
    description: "Aggressive tread and waterproof design for off-road adventures.",
    price: 149.99,
    category: ["running", "footwear"],
    weather: ["rain", "mud", "all-weather"],
    activities: ["trail running", "hiking"],
    image: "https://images.asics.com/is/image/asics/1011B700_401_SR_RT_GLB?$sfcc-product$",
  },
  {
    id: "running-race-flats",
    name: "Carbon-Plated Racing Shoes",
    description: "Ultra-light and responsive design for marathon racing.",
    price: 249.99,
    category: ["running", "footwear"],
    weather: ["all-weather"],
    activities: ["marathon", "race day"],
    image: "https://hips.hearstapps.com/hmg-prod/images/best-carbon-plate-shoes-6478ef7ee3f19.jpg?crop=0.6666666666666666xw:1xh;center,top&resize=1200:*",
  },
  {
    id: "running-shirt-mens",
    name: "Men's Moisture-Wicking Running Shirt",
    description: "Breathable, sweat-resistant fabric for hot-weather runs.",
    price: 34.99,
    category: ["running", "clothing"],
    weather: ["warm", "hot"],
    activities: ["running", "training"],
    image: "https://pyxis.nymag.com/v1/imgs/9b2/dd4/5c79a858455045d558072a97399dc0caad-1----.rhorizontal.w600.jpg",
  },
  {
    id: "running-shirt-womens",
    name: "Women's Lightweight Running Tank",
    description: "Racerback cut for comfort and ventilation in warm weather.",
    price: 29.99,
    category: ["running", "clothing"],
    weather: ["warm", "hot"],
    activities: ["running", "training"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPN4I6ZmGR5IPY5DqBLNNEph-taLp06yy7jw&s",
  },
  {
    id: "running-shorts-mens",
    name: "Men's 5-inch Running Shorts",
    description: "Lightweight and breathable with built-in liner.",
    price: 44.99,
    category: ["running", "clothing"],
    weather: ["warm", "hot"],
    activities: ["running", "marathon"],
    image: "https://www.craftsports.us/cdn/shop/products/1908763-999000.jpg?v=1656684450",
  },
  {
    id: "running-shorts-womens",
    name: "Women's High-Waist Running Shorts",
    description: "Supportive, quick-dry shorts with a zip pocket.",
    price: 39.99,
    category: ["running", "clothing"],
    weather: ["warm", "hot"],
    activities: ["running", "training"],
    image: "https://target.scene7.com/is/image/Target/GUEST_cf905426-8d0a-4383-b7a4-5b30d847e5d0?wid=300&hei=300&fmt=pjpeg",
  },
  {
    id: "running-tights-mens",
    name: "Men's Compression Running Tights",
    description: "Keeps muscles warm and reduces fatigue on long runs.",
    price: 59.99,
    category: ["running", "clothing"],
    weather: ["cold", "mild"],
    activities: ["running", "training"],
    image: "https://supacore.com/cdn/shop/files/PRODUCTIMAGES_29_600x.png?v=1732288283",
  },
  {
    id: "running-leggings-womens",
    name: "Women's Thermal Running Leggings",
    description: "Brushed fleece interior for warmth and moisture control.",
    price: 69.99,
    category: ["running", "clothing"],
    weather: ["cold"],
    activities: ["running", "training"],
    image: "https://www.pearlizumi.com/cdn/shop/files/fe49db15e822d599d47645bd5a0bf8974a84e079_1000x.png?v=1735879657",
  },
  {
    id: "running-windbreaker",
    name: "Ultralight Running Windbreaker",
    description: "Packable and water-resistant for breezy conditions.",
    price: 89.99,
    category: ["running", "clothing"],
    weather: ["wind", "mild"],
    activities: ["running", "training"],
    image: "https://cdn.4f.com.pl/media/catalog/product/cache/c7948d663b21982fa4a80ec214224aae/4/F/4FWAW24TTJAM553-22S-P-01-MAIN.jpg",
  },
  {
    id: "running-rain-jacket",
    name: "Breathable Waterproof Running Jacket",
    description: "Stay dry without overheating on wet runs.",
    price: 129.99,
    category: ["running", "clothing"],
    weather: ["rain"],
    activities: ["running", "marathon"],
    image: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1706013649-best-running-jackets-under-armour-65afb3b812792.png?crop=1xw:1xh;center,top&resize=980:*",
  },
  {
    id: "running-headlamp",
    name: "Rechargeable Running Headlamp",
    description: "Bright LED with adjustable strap for night runs.",
    price: 39.99,
    category: ["running", "accessories"],
    weather: ["all-weather"],
    activities: ["running", "trail running"],
    image: "https://www.ledlenserusa.com/cdn/shop/products/NEO9R_gray_502324_standard_laying_headstrap.png?v=1648706090",
  },
  {
    id: "running-hydration-belt",
    name: "Hydration Running Belt",
    description: "Bounce-free belt with dual water bottles and pockets.",
    price: 49.99,
    category: ["running", "accessories"],
    weather: ["warm", "hot"],
    activities: ["running", "marathon"],
    image: "https://m.media-amazon.com/images/I/61I1u8TvGqS._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: "running-smartwatch",
    name: "GPS Running Smartwatch",
    description: "Track pace, heart rate, and VO2 max with precision.",
    price: 299.99,
    category: ["running", "electronics"],
    weather: ["all-weather"],
    activities: ["running", "training"],
    image: "https://i5.walmartimages.com/seo/Forerunner-245-GPS-Running-Smartwatch-in-Slate-Gray_d5f7e3aa-9a9b-458f-9819-10f2cdb979a0.7b73ae7871a4fab911577395ca16c9cc.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
  },
  {
    id: "running-compression-socks",
    name: "Compression Running Socks",
    description: "Improves circulation and reduces muscle fatigue.",
    price: 29.99,
    category: ["running", "clothing"],
    weather: ["all-weather"],
    activities: ["running", "marathon"],
    image: "https://www.sidas.com/cdn/shop/files/endurance-racing-knee.jpg?v=1722507697",
  },
  {
    id: "running-sunglasses",
    name: "Polarized Running Sunglasses",
    description: "Lightweight UV-protected lenses for bright conditions.",
    price: 79.99,
    category: ["running", "accessories"],
    weather: ["sunny"],
    activities: ["running", "trail running"],
    image: "https://m.media-amazon.com/images/I/61z7lE2pwvL._AC_UY1000_.jpg",
  },
  {
    id: "mens-swim-trunks",
    name: "Men's Quick-Dry Swim Trunks",
    description: "Comfortable swim shorts with mesh lining and side pockets.",
    price: 34.99,
    category: ["swimming", "clothing"],
    weather: ["warm", "hot"],
    activities: ["swimming", "beach"],
    image: "https://www.legendarywhitetails.com/dw/image/v2/BLJD_PRD/on/demandware.static/-/Sites-master-us/default/dwf8c8d74f/images/mens-quick-dry-topographical-print-swim-trunks-1024-AEGT-front-laydown.jpg?sw=800&sh=800&sm=fit",
  },
  {
    id: "womens-one-piece",
    name: "Women's Athletic One-Piece Swimsuit",
    description: "Chlorine-resistant swimsuit with moderate coverage and cross-back straps.",
    price: 49.99,
    category: ["swimming", "clothing"],
    weather: ["warm", "hot"],
    activities: ["swimming", "beach"],
    image: "https://metroswimshop.com/cdn/shop/products/2A192_907_700x.jpg?v=1700053365",
  },
  {
    id: "womens-two-piece",
    name: "Women's Sport Bikini Set",
    description: "Athletic two-piece with racerback top and full coverage bottom.",
    price: 44.99,
    category: ["swimming", "clothing"],
    weather: ["warm", "hot"], 
    activities: ["swimming", "beach"],
    image: "https://www.bfgcdn.com/1500_1500_90/150-2788-0111/oneill-womens-sport-bikini-set-bikini.jpg",
  },
  {
    id: "board-shorts",
    name: "Long Board Shorts",
    description: "Quick-drying board shorts with UPF 50+ protection.",
    price: 39.99,
    category: ["swimming", "clothing"],
    weather: ["warm", "hot"],
    activities: ["swimming", "beach", "surfing"],
    image: "https://www.uvskinz.com/cdn/shop/files/060237-BalticAztecStripe-1_1024x.jpg?v=1710181826",
  },
  {
    id: "fishing-rod-carbon",
    name: "Carbon Fiber Fishing Rod",
    description: "Lightweight and durable fishing rod, perfect for freshwater and saltwater fishing.",
    price: 129.99,
    category: ["fishing", "gear"],
    weather: ["all-weather"],
    activities: ["fishing"],
    image: "https://m.media-amazon.com/images/I/61bk53mFRHL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: "fishing-reel",
    name: "High-Speed Spinning Reel",
    description: "Smooth performance with corrosion-resistant bearings, ideal for both fresh and saltwater.",
    price: 89.99,
    category: ["fishing", "gear"],
    weather: ["all-weather"],
    activities: ["fishing"],
    image: "https://www.pennfishing.com/cdn/shop/files/Penn_Battle_III_6000_HS_Reel_2020_alt1.jpg?v=1703014585",
  },
  {
    id: "fishing-tackle-box",
    name: "Waterproof Fishing Tackle Box",
    description: "Organized storage for lures, hooks, and fishing accessories.",
    price: 39.99,
    category: ["fishing", "storage"],
    weather: ["all-weather"],
    activities: ["fishing"],
    image: "https://m.media-amazon.com/images/I/71UFosiZvZL.jpg",
  },
  {
    id: "fishing-bait-kit",
    name: "Deluxe Fishing Bait Kit",
    description: "A selection of artificial baits and lures for a variety of fish species.",
    price: 49.99,
    category: ["fishing", "gear"],
    weather: ["all-weather"],
    activities: ["fishing"],
    image: "https://m.media-amazon.com/images/I/81pnIglAAUL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: "fishing-waders",
    name: "Chest-High Fishing Waders",
    description: "Waterproof and breathable waders with reinforced knee protection.",
    price: 159.99,
    category: ["fishing", "clothing"],
    weather: ["cold", "mild"],
    activities: ["fishing"],
    image: "https://cdn.shopify.com/s/files/1/0843/5066/5022/products/DEZ-Chest-Wader-Front_400x400.jpg?v=1701937451",
  },
  {
    id: "fishing-vest",
    name: "Multi-Pocket Fishing Vest",
    description: "Lightweight vest with multiple pockets for tackle and gear.",
    price: 79.99,
    category: ["fishing", "clothing"],
    weather: ["mild", "warm"],
    activities: ["fishing"],
    image: "https://i5.walmartimages.com/seo/Mesh-Fishing-Vest-Lightweight-with-Multi-Pocket-Camping-Travel-Training_8c25c3d4-f7b5-4bee-91a9-b43009a79bca.98188f5c4dd39311f4a9d9e94dcd21dc.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
  }  ,
  {
    id: "softshell-vest",
    name: "Men’s Softshell Vest",
    description: "Wind and water-resistant vest with fleece lining for core warmth.",
    price: 99.99,
    category: ["clothing", "outerwear"],
    weather: ["mild", "wind"],
    activities: ["hiking", "camping"],
    image: "https://www.stormtechusa.com/cdn/shop/products/KSV-1_FRONT_DOLPHIN_05279bfd-918e-4e51-afed-c1428131bf0c.jpg?v=1736184846&width=1200",
  },
  {
    id: "fleece-vest",
    name: "Women’s Fleece Vest",
    description: "Lightweight and warm vest for layering during outdoor activities.",
    price: 79.99,
    category: ["clothing", "outerwear"],
    weather: ["mild", "cold"],
    activities: ["hiking", "camping", "casual"],
    image: "https://www.burgeonoutdoor.com/cdn/shop/products/1_56ea59e3-aec0-45e2-9ecf-4ceceff31ba7.jpg?v=1665064370&width=512",
  },
  {
    id: "athletic-tank-mens",
    name: "Men’s Performance Tank Top",
    description: "Moisture-wicking and breathable tank top for active wear.",
    price: 34.99,
    category: ["clothing"],
    weather: ["warm", "hot"],
    activities: ["hiking", "running", "gym"],
    image: "https://www.boathouse.com/cdn/shop/products/men-s-performance-dri-tank-top-ctm320-fadedblue-sml-31237243142234_1400x.jpg?v=1686065561",
  },
  {
    id: "athletic-tank-womens",
    name: "Women’s Performance Tank Top",
    description: "Lightweight and sweat-resistant tank for high-intensity workouts.",
    price: 34.99,
    category: ["clothing"],
    weather: ["warm", "hot"],
    activities: ["hiking", "running", "gym"],
    image: "https://franklinsports.com/media/catalog/product/cache/421465681dac8f59ae2e23f878a9878a/5/2/52760c3fx-phase1-main_6.jpg",
  },
  {
    id: "long-sleeve-hiking-shirt",
    name: "Long-Sleeve UPF Hiking Shirt",
    description: "Sun-protective, quick-dry shirt for long outdoor adventures.",
    price: 59.99,
    category: ["clothing", "sun-protection"],
    weather: ["warm", "mild"],
    activities: ["hiking", "camping", "fishing"],
    image: "https://i5.walmartimages.com/seo/33-000ft-Men-s-UPF-50-UV-Protection-Long-Sleeve-Hiking-Shirts-Breathable-Quick-Dry-Fishing-Shirts-for-Safari-Outdoor_6bf2b948-1a24-466e-af53-32ff4bb7da30.5db9e79e1799f723391b5b18f70e3810.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
  },
  {
    id: "hiking-wipes",
    name: "Biodegradable Body Wipes",
    description: "Gentle, unscented body wipes for keeping clean on multi-day hikes.",
    price: 12.99,
    category: ["hygiene", "camping"],
    weather: ["all-weather"],
    activities: ["hiking", "camping", "backpacking"],
    image: "https://shoppinkattitude.com/cdn/shop/files/64f9c1c10900927a612fd526e36a3a18c0e4ac6292e0a2e5ae018f55b3f6bd41_1024x1024@2x.jpg?v=1713976204",
  },
  {
    id: "hand-sanitizer-gel",
    name: "Travel-Sized Antibacterial Gel",
    description: "Kills 99.99% of germs, compact for backpacking and outdoor use.",
    price: 4.99,
    category: ["hygiene", "safety"],
    weather: ["all-weather"],
    activities: ["hiking", "camping", "travel"],
    image: "https://image.made-in-china.com/2f0j00gEGUduiIVsrH/Clip-on-Travel-Size-Antibacterial-Hand-Sanitizer-Gel.webp",
  },
  {
    id: "camping-soap",
    name: "Eco-Friendly Campsuds Camping Soap",
    description: "Biodegradable soap for washing dishes, hands, and even clothes.",
    price: 9.99,
    category: ["hygiene", "camping"],
    weather: ["all-weather"],
    activities: ["camping", "backpacking"],
    image: "https://www.lowergear.com/img/p/8/1/9/819-tm_thickbox_default.jpg",
  },
  {
    id: "quick-dry-towel",
    name: "Quick-Dry Microfiber Towel",
    description: "Absorbent and compact, perfect for outdoor adventures.",
    price: 24.99,
    category: ["hygiene", "camping"],
    weather: ["all-weather"],
    activities: ["hiking", "camping", "swimming"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzscIC1dcqeHeHNuIdX-fIN9jj2Ft8rXAGqQ&s",
  },
  {
    id: "ski-jacket-mens",
    name: "Men's Insulated Ski Jacket",
    description: "Waterproof, breathable, and insulated for warmth on the slopes.",
    price: 249.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "extreme-cold", "snow"],
    activities: ["skiing", "snowboarding"],
    image: "https://cdni.llbean.net/is/image/wim/520856_49200_41?hei=1095&wid=950&resMode=sharp2&defaultImage=llbprod/520856_49200_41",
  },
  {
    id: "ski-jacket-womens",
    name: "Women's Insulated Ski Jacket",
    description: "Designed for performance and style, featuring a snow skirt and adjustable hood.",
    price: 249.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "extreme-cold", "snow"],
    activities: ["skiing", "snowboarding"],
    image: "https://cdni.llbean.net/is/image/wim/520860_56288_41?hei=1095&wid=950&resMode=sharp2&defaultImage=llbprod/520860_56288_41",
  },
  {
    id: "ski-pants-mens",
    name: "Men's Waterproof Ski Pants",
    description: "Fully seam-sealed pants with reinforced knees for extra durability.",
    price: 199.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "snow"],
    activities: ["skiing", "snowboarding"],
    image: "https://rehall.com/cdn/shop/files/26c526b0-a56f-4eb1-9d62-a24084fedff8.jpg?v=1729571869",
  },
  {
    id: "ski-pants-womens",
    name: "Women's Waterproof Ski Pants",
    description: "Lightweight, insulated pants with snow gaiters to keep out powder.",
    price: 199.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "snow"],
    activities: ["skiing", "snowboarding"],
    image: "https://elevenate.com/_next/image?url=https%3A%2F%2Felevenate.centracdn.net%2Fclient%2Fdynamic%2Fimages%2F704_bec8066b3d-216-22557-1-full.jpg&w=3840&q=75",
  },
  {
    id: "ski-gloves",
    name: "Insulated Ski Gloves",
    description: "Windproof, waterproof gloves with touchscreen-compatible fingertips.",
    price: 89.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "extreme-cold", "snow"],
    activities: ["skiing", "snowboarding"],
    image: "https://m.media-amazon.com/images/I/81susELcpTL._AC_UY1000_.jpg",
  },
  {
    id: "ski-goggles",
    name: "Anti-Fog Ski Goggles",
    description: "UV-protected, anti-fog lenses with wide peripheral vision.",
    price: 99.99,
    category: ["accessories", "ski", "snow"],
    weather: ["cold", "snow", "sunny"],
    activities: ["skiing", "snowboarding"],
    image: "https://cdn11.bigcommerce.com/s-6ravsmq/images/stencil/1500x1500/products/2264/12711/09ef769cd3810f781e8ece5b8f6c816e_720x__12425.1669744127.jpg?c=2",
  },
  {
    id: "ski-helmet",
    name: "Lightweight Ski Helmet",
    description: "Impact-resistant and breathable with an adjustable fit.",
    price: 129.99,
    category: ["safety", "ski", "snow"],
    weather: ["cold", "snow"],
    activities: ["skiing", "snowboarding"],
    image: "https://cdni.llbean.net/is/image/wim/509207_1486_41?hei=1095&wid=950&resMode=sharp2&defaultImage=llbprod/509207_1486_41",
  },
  {
    id: "ski-socks",
    name: "Thermal Merino Wool Ski Socks",
    description: "Moisture-wicking and extra warm for long days in the snow.",
    price: 29.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "extreme-cold"],
    activities: ["skiing", "snowboarding"],
    image: "https://m.media-amazon.com/images/I/81-Zj7fYa7L._AC_UY1000_.jpg",
  },
  {
    id: "ski-boot-bag",
    name: "Padded Ski Boot Bag",
    description: "Durable, waterproof bag to transport ski boots and gear.",
    price: 79.99,
    category: ["bags", "ski", "travel"],
    weather: ["all-weather"],
    activities: ["skiing", "snowboarding", "travel"],
    image: "https://cdn11.bigcommerce.com/s-x0wq46vtjo/images/stencil/1280x1280/products/122/1411/thermal-trekker-heated-ski-boot-bag-in-diamond-grey-black-white-angel-right-view-1__16470.1694807701.jpg?c=1",
  },
  {
    id: "heated-gloves",
    name: "Battery-Powered Heated Gloves",
    description: "Rechargeable gloves that provide up to 8 hours of warmth.",
    price: 149.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["extreme-cold"],
    activities: ["skiing", "snowboarding", "mountaineering"],
    image: "https://www.ororowear.com/cdn/shop/files/1_23cfc84b-8938-40dd-85bb-0d75dce4cd51.jpg?v=1687683683",
  },
  {
    id: "heated-socks",
    name: "Electric Heated Ski Socks",
    description: "Adjustable temperature control keeps feet warm in freezing conditions.",
    price: 129.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["extreme-cold"],
    activities: ["skiing", "snowboarding", "hiking"],
    image: "https://ae01.alicdn.com/kf/S39d74c8145b84142ba982579eff97344V.jpg",
  },
  {
    id: "snowshoes",
    name: "Aluminum Frame Snowshoes",
    description: "Lightweight and durable for easy travel over deep snow.",
    price: 179.99,
    category: ["footwear", "winter-gear", "snow"],
    weather: ["cold", "snow"],
    activities: ["snowshoeing", "hiking"],
    image: "https://cdn11.bigcommerce.com/s-dses6v/images/stencil/1280x1280/products/7865/48134/AT4__31519.1645044064.jpg?c=2?imbypass=on",
  },
  {
    id: "ski-backpack",
    name: "Ski Touring Backpack",
    description: "Hydration-compatible pack with ski-carry straps and avalanche tool storage.",
    price: 149.99,
    category: ["bags", "ski", "safety"],
    weather: ["cold", "snow"],
    activities: ["skiing", "snowboarding", "mountaineering"],
    image: "https://dxtb1rh8tbbvs.cloudfront.net/cache-buster-11738887747/ORTOVOX/mediaroom-product-archive/Backpacks/Ski%20touring%20backpacks/320717/image-thumb__320717__pds__product_png/46484-88201-HAUTE_ROUTE_32_arctic_grey-B-01.png",
  },
  {
    id: "avalanche-beacon",
    name: "Avalanche Rescue Beacon",
    description: "Essential for backcountry safety, fast and accurate location tracking.",
    price: 299.99,
    category: ["safety", "ski"],
    weather: ["cold", "snow"],
    activities: ["backcountry skiing", "snowboarding", "mountaineering"],
    image: "https://i5.walmartimages.com/seo/Backcountry-Access-Tracker-S-Avalanche-Beacon_b03c5236-a3a9-4c86-8b7e-d042e567a28f.6a03a700d564f4cc5f8ed7351709ce92.jpeg",
  },
  {
    id: "balaclava",
    name: "Thermal Fleece Balaclava",
    description: "Full face protection against wind and extreme cold.",
    price: 24.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "wind", "snow"],
    activities: ["skiing", "snowboarding", "mountaineering"],
    image: "https://rockbrosusa.com/cdn/shop/files/1_1412e9c4-51b4-410f-bd9b-a57ce19f8be5.jpg?v=1731907719&width=2048",
  }  
]
