export interface Product {
  id: string
  name: string
  description: string
  price: number
  category: string[]
  weather: string[]
  activities: string[]
  image: string
}

export const products: Product[] = [
  {
    id: "sleeping-bag-winter",
    name: "Alpine Winter Sleeping Bag",
    description: "Rated for temperatures down to -20°F, perfect for tall individuals up to 6'6\"",
    price: 299.99,
    category: ["sleeping", "winter-gear"],
    weather: ["cold", "extreme-cold"],
    activities: ["camping", "mountaineering"],
    image: "https://www.militarykit.com/cdn/shop/products/snugpak-navigator-sleeping-bag-olive_grande.jpg?v=1581436850",
  },
  {
    id: "tent-tall",
    name: "Wilderness Extended Height Tent",
    description: "3-season tent with 7' center height, ideal for tall campers",
    price: 449.99,
    category: ["shelter", "tents"],
    weather: ["mild", "cold", "rain"],
    activities: ["camping", "backpacking"],
    image: "https://www.bigagnes.com/cdn/shop/files/Blacktail-3-Hotel-01_600x.png?v=1734723376",
  },
  {
    id: "insulated-jacket",
    name: "Mountain Pro Insulated Jacket",
    description: "Tall sizes available, waterproof and breathable winter jacket",
    price: 299.99,
    category: ["clothing", "winter-gear"],
    weather: ["cold", "extreme-cold", "wind", "rain"],
    activities: ["hiking", "camping", "mountaineering"],
    image: "https://cdn11.bigcommerce.com/s-nea9lcsxle/images/stencil/1280x1280/products/14831/19037/bc636764Screenshot%202023-10-03%20103226__07751.1696343591.png?c=1",
  },
  {
    id: "hiking-boots",
    name: "All-Terrain Hiking Boots",
    description: "Waterproof hiking boots with excellent ankle support, available in extended sizes",
    price: 189.99,
    category: ["footwear"],
    weather: ["all-weather"],
    activities: ["hiking", "backpacking", "mountaineering"],
    image: "https://meindlusa.com/cdn/shop/files/LadyKansas_Main_10920f4b-b36d-4383-aa45-3604fafe0c5f_1024x.png?v=1715187719",
  },
  {
    id: "climbing-shoes",
    name: "Rock Climbing Shoes",
    description: "Top of the line climbing shoes. Climb harder and longer, suffer less, available in extended sizes",
    price: 89.99,
    category: ["footwear", "rock climbing"],
    weather: ["all-weather"],
    activities: ["climbing", "rock climbing", "mountaineering"],
    image: "https://lcdn.lasportivausa.com/pub/media/catalog/product/z/f/zfcs005_k00y00_skwama_blackyellow_3_4.jpg?width=700&height=700&store=en&image-type=image",
  },
  {
    id: "climbing-harness",
    name: "Rock Climbing Harness",
    description: "Gear you can trust. All you need for gym and crag climbing, and it's built in an environmentally friendly way.",
    price: 69.99,
    category: ["rock climbing"],
    weather: ["all-weather"],
    activities: ["rock climbing", "mountaineering"],
    image: "https://m.media-amazon.com/images/I/71jGNwa-TiL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: "backpack-65l",
    name: "Expedition 65L Backpack",
    description: "Large capacity backpack with adjustable torso length for tall hikers",
    price: 279.99,
    category: ["bags", "backpacks"],
    weather: ["all-weather"],
    activities: ["hiking", "backpacking", "camping"],
    image: "https://cdni.llbean.net/is/image/wim/520605_53152_44?hei=1095&wid=950&resMode=sharp2&defaultImage=llbprod/520605_53152_41",
  },
  {
    id: "trekking-poles",
    name: "Carbon Fiber Trekking Poles",
    description: "Adjustable length trekking poles with cork grips",
    price: 129.99,
    category: ["accessories"],
    weather: ["all-weather"],
    activities: ["hiking", "backpacking", "mountaineering"],
    image: "https://cdn11.bigcommerce.com/s-hgn1l9sh63/product_images/attribute_rule_images/22705_source_1706770861.jpg",
  },
  {
    id: "camp-stove",
    name: "Ultralight Camp Stove",
    description: "Compact and efficient camp stove for backcountry cooking",
    price: 69.99,
    category: ["cooking", "camp-kitchen"],
    weather: ["all-weather"],
    activities: ["camping", "backpacking"],
    image: "https://gofsr.com/cdn/shop/files/PortableCampStove_WhiteCyc-32.jpg?v=1723055456&width=3000",
  },
  {
    id: "water-filter",
    name: "Advanced Water Filtration System",
    description: "Removes 99.99999% of waterborne bacteria and protozoa",
    price: 39.99,
    category: ["water", "safety"],
    weather: ["all-weather"],
    activities: ["camping", "hiking", "backpacking"],
    image: "https://www.aosmithatlowes.com/media/1104/ao-mf-adv-main.png",
  },
  {
    id: "down-jacket",
    name: "Ultralight Down Jacket",
    description: "800-fill power down jacket, packs into its own pocket",
    price: 249.99,
    category: ["clothing", "winter-gear"],
    weather: ["cold", "mild"],
    activities: ["hiking", "camping", "casual"],
    image: "https://www.logowearplus.com/v/vspfiles/photos/84757-2T.jpg",
  },
  {
    id: "rain-shell",
    name: "Lightweight Rain Shell",
    description: "Waterproof and breathable rain jacket with pit zips",
    price: 169.99,
    category: ["clothing", "rain-gear"],
    weather: ["rain", "wind"],
    activities: ["hiking", "camping", "casual"],
    image: "https://www.adventurealan.com/wp-content/uploads/2021/03/Enlightened-Equipment-Visp-Rain-Jacket.jpg",
  },
  {
    id: "hiking-pants",
    name: "Convertible Hiking Pants",
    description: "Quick-dry convertible pants with UPF 50+ protection",
    price: 89.99,
    category: ["clothing"],
    weather: ["mild", "warm"],
    activities: ["hiking", "camping", "casual"],
    image: "https://www.adventurealan.com/wp-content/uploads/2021/04/REI-Co-op-Sahara-convertible-Pants.jpg",
  },
  {
    id: "headlamp",
    name: "Rechargeable Headlamp",
    description: "350 lumens LED headlamp with red night vision mode",
    price: 49.99,
    category: ["accessories", "lighting"],
    weather: ["all-weather"],
    activities: ["camping", "hiking", "emergency"],
    image: "https://policesecurity.com/cdn/shop/files/98730-BLACKOUT-R-HERO-SHADOW_1200x.jpg?v=1738787613",
  },
  {
    id: "bear-canister",
    name: "Bear-Resistant Food Container",
    description: "Required for many wilderness areas, protects your food from wildlife",
    price: 79.99,
    category: ["food-storage", "safety"],
    weather: ["all-weather"],
    activities: ["camping", "backpacking"],
    image: "https://m.media-amazon.com/images/I/81g0EfnvsVL.jpg",
  },
  {
    id: "sleeping-pad",
    name: "Insulated Sleeping Pad",
    description: "4-season sleeping pad with R-value of 6.9",
    price: 179.99,
    category: ["sleeping"],
    weather: ["all-weather", "cold"],
    activities: ["camping", "backpacking"],
    image: "https://whaletalesarchery.com/wp-content/uploads/2022/06/Klymit_InsulatedStaticV_06IVOR01C_AngleBag_v1_2000x2000_99bd02f2-bfc9-4199-bc9e-6123eb0b33a9_5000x.webp",
  },
  {
    id: "camp-chair",
    name: "Packable Camp Chair",
    description: "Comfortable and lightweight, supports up to 300 lbs",
    price: 99.99,
    category: ["furniture", "comfort"],
    weather: ["all-weather"],
    activities: ["camping", "outdoor-events"],
    image: "https://cascademountaintech.com/cdn/shop/products/HBS-GR-21200x1200.jpg?v=1653559369",
  },
  {
    id: "hiking-socks-merino",
    name: "Merino Wool Hiking Socks",
    description: "Moisture-wicking, odor-resistant wool socks for long hikes",
    price: 24.99,
    category: ["clothing", "footwear"],
    weather: ["cold", "mild"],
    activities: ["hiking", "camping", "backpacking"],
    image: "https://www.gowithsocks.com/cdn/shop/files/merino-wool-hiking-socks-green-2-pairs.webp?v=1704644326",
  },
  {
    id: "thermal-socks",
    name: "Extreme Cold Thermal Socks",
    description: "Designed for freezing temperatures, extra thick and warm",
    price: 29.99,
    category: ["clothing", "winter-gear"],
    weather: ["cold", "extreme-cold"],
    activities: ["camping", "mountaineering"],
    image: "https://cdn11.bigcommerce.com/s-skjz97mme0/images/stencil/500x659/products/122/662/Blue-Flame-E-Tech-Bamboo-Thermal-Socks-Group__05880.1605762174.jpg?c=2",
  },
  {
    id: "base-layer-top",
    name: "Moisture-Wicking Base Layer Top",
    description: "Breathable and quick-drying base layer for active wear",
    price: 59.99,
    category: ["clothing"],
    weather: ["all-weather"],
    activities: ["hiking", "camping", "mountaineering"],
    image: "https://www.rei.com/media/993d8470-f5f7-416d-b79a-537a50d910d5.jpg",
  },
  {
    id: "flannel-shirt",
    name: "Heavy-Duty Outdoor Flannel",
    description: "Durable, warm, and stylish flannel shirt for outdoor adventures",
    price: 69.99,
    category: ["clothing"],
    weather: ["mild", "cold"],
    activities: ["camping", "casual"],
    image: "https://cdn11.bigcommerce.com/s-20kzykhhd5/images/stencil/1280x1280/products/3319/14726/WS04-RDPL_front__98832.1736891488.jpg?c=2",
  },
  {
    id: "softshell-pants",
    name: "Softshell Hiking Pants",
    description: "Wind and water-resistant pants for tough conditions",
    price: 119.99,
    category: ["clothing"],
    weather: ["cold", "wind"],
    activities: ["hiking", "mountaineering"],
    image: "https://www.snowpeak.com/cdn/shop/products/PA-24SU006_Slateblue_P_01_png.png?v=1709154872",
  },
  {
    id: "thermal-leggings",
    name: "Thermal Leggings",
    description: "Insulated leggings for extra warmth in winter conditions",
    price: 79.99,
    category: ["clothing", "winter-gear"],
    weather: ["cold"],
    activities: ["camping", "skiing"],
    image: "https://cdn11.bigcommerce.com/s-r4f6haoaux/images/stencil/1280x1280/products/167/684/mens-heavyweight-thermal-bottom-long-underwear-natural-Polar-King-173-10-front__56263.1582847657.jpg?c=1",
  },
  {
    id: "hiking-shorts",
    name: "Trail-Ready Hiking Shorts",
    description: "Lightweight and breathable shorts with multiple pockets",
    price: 54.99,
    category: ["clothing"],
    weather: ["warm"],
    activities: ["hiking", "camping"],
    image: "https://www.rei.com/media/product/2426450017",
  },
  {
    id: "winter-gloves",
    name: "Extreme Cold Winter Gloves",
    description: "Waterproof, insulated gloves for sub-zero temperatures",
    price: 89.99,
    category: ["clothing", "winter-gear"],
    weather: ["cold", "extreme-cold"],
    activities: ["camping", "mountaineering"],
    image: "https://www.westmarine.com/on/demandware.static/-/Sites-wm-master-catalog/default/dw73efd5eb/images/orig/P019634344_BLACK_1500.19072019023109.jpg",
  },
  {
    id: "lightweight-gloves",
    name: "Lightweight Trail Gloves",
    description: "Flexible and breathable gloves for mild weather",
    price: 34.99,
    category: ["clothing"],
    weather: ["mild"],
    activities: ["hiking", "trail running"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "beanie",
    name: "Merino Wool Beanie",
    description: "Warm and breathable, fits under helmets",
    price: 29.99,
    category: ["clothing"],
    weather: ["cold"],
    activities: ["camping", "hiking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "sun-hat",
    name: "Wide-Brim Sun Hat",
    description: "UPF 50+ protection, moisture-wicking sweatband",
    price: 39.99,
    category: ["clothing"],
    weather: ["warm"],
    activities: ["hiking", "camping"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "high-end-sleeping-bag",
    name: "Expedition Down Sleeping Bag",
    description: "Rated for -40°F, ultralight and highly compressible",
    price: 799.99,
    category: ["sleeping", "winter-gear"],
    weather: ["extreme-cold"],
    activities: ["mountaineering", "arctic expeditions"],
    image: "https://target.scene7.com/is/image/Target/GUEST_50dba949-9f36-427f-86d6-a895c2143fe3",
  },
  {
    id: "gps-watch",
    name: "Adventure GPS Smartwatch",
    description: "Track routes, monitor altitude, and measure heart rate",
    price: 499.99,
    category: ["electronics", "accessories"],
    weather: ["all-weather"],
    activities: ["hiking", "mountaineering", "running", "camping"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "basic-camping-mug",
    name: "Stainless Steel Camping Mug",
    description: "Durable and lightweight, perfect for coffee by the campfire",
    price: 9.99,
    category: ["camp-kitchen"],
    weather: ["all-weather"],
    activities: ["camping", "backpacking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "budget-rain-jacket",
    name: "Budget Waterproof Rain Jacket",
    description: "Affordable rain protection, lightweight and packable",
    price: 49.99,
    category: ["clothing", "rain-gear"],
    weather: ["rain", "wind"],
    activities: ["hiking", "casual"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "cheap-camping-chair",
    name: "Basic Folding Camping Chair",
    description: "Lightweight and easy to pack, great for quick trips",
    price: 39.99,
    category: ["furniture", "comfort"],
    weather: ["all-weather"],
    activities: ["camping", "outdoor-events"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "bike-helmet-pro",
    name: "Pro Cycling Helmet",
    description: "Lightweight, aerodynamic helmet with advanced ventilation and MIPS safety system.",
    price: 149.99,
    category: ["biking", "safety"],
    weather: ["all-weather"],
    activities: ["cycling", "mountain biking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "mtb-full-face-helmet",
    name: "Full-Face MTB Helmet",
    description: "Downhill mountain biking helmet with extended protection and impact resistance.",
    price: 199.99,
    category: ["biking", "safety"],
    weather: ["all-weather"],
    activities: ["mountain biking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "cycling-gloves-summer",
    name: "Breathable Cycling Gloves",
    description: "Fingerless padded gloves for long rides with excellent grip.",
    price: 29.99,
    category: ["biking", "clothing"],
    weather: ["mild", "warm"],
    activities: ["cycling"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "cycling-gloves-winter",
    name: "Winter Cycling Gloves",
    description: "Windproof and waterproof gloves with touchscreen compatibility.",
    price: 49.99,
    category: ["biking", "clothing", "winter-gear"],
    weather: ["cold", "wind"],
    activities: ["cycling", "mountain biking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "cycling-bib-shorts",
    name: "Cycling Bib Shorts",
    description: "Padded, moisture-wicking bib shorts for maximum comfort on long rides.",
    price: 89.99,
    category: ["biking", "clothing"],
    weather: ["warm"],
    activities: ["cycling"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "mountain-bike-shorts",
    name: "Mountain Biking Shorts",
    description: "Durable and flexible MTB shorts with multiple pockets.",
    price: 74.99,
    category: ["biking", "clothing"],
    weather: ["mild", "warm"],
    activities: ["mountain biking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "cycling-shoes-road",
    name: "Road Cycling Shoes",
    description: "Stiff carbon sole and BOA closure for optimal pedaling efficiency.",
    price: 199.99,
    category: ["biking", "footwear"],
    weather: ["all-weather"],
    activities: ["cycling"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "cycling-shoes-mtb",
    name: "Mountain Biking Shoes",
    description: "Grippy soles and SPD compatibility for trail riding.",
    price: 149.99,
    category: ["biking", "footwear"],
    weather: ["all-weather"],
    activities: ["mountain biking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "cycling-windbreaker",
    name: "Packable Cycling Windbreaker",
    description: "Ultralight, windproof jacket that fits into a jersey pocket.",
    price: 79.99,
    category: ["biking", "clothing"],
    weather: ["wind", "mild"],
    activities: ["cycling"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "cycling-rain-jacket",
    name: "Waterproof Cycling Jacket",
    description: "Breathable and waterproof shell with reflective details.",
    price: 129.99,
    category: ["biking", "clothing", "rain-gear"],
    weather: ["rain", "wind"],
    activities: ["cycling"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "bike-light-front",
    name: "High-Lumen Bike Headlight",
    description: "Rechargeable front light with 1200 lumens for night rides.",
    price: 59.99,
    category: ["biking", "electronics"],
    weather: ["all-weather"],
    activities: ["cycling", "mountain biking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "bike-light-rear",
    name: "USB Rechargeable Rear Bike Light",
    description: "Ultra-bright red LED with multiple flashing modes for safety.",
    price: 29.99,
    category: ["biking", "electronics"],
    weather: ["all-weather"],
    activities: ["cycling"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "bike-pump",
    name: "Portable Bike Pump",
    description: "Lightweight, high-pressure pump for road and mountain bikes.",
    price: 34.99,
    category: ["biking", "accessories"],
    weather: ["all-weather"],
    activities: ["cycling", "mountain biking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "bike-repair-kit",
    name: "Complete Bike Repair Kit",
    description: "Includes multi-tool, tire levers, and patches for on-the-go fixes.",
    price: 44.99,
    category: ["biking", "accessories"],
    weather: ["all-weather"],
    activities: ["cycling", "mountain biking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "hydration-pack",
    name: "Cycling Hydration Pack",
    description: "Lightweight backpack with a 2L water reservoir for long rides.",
    price: 69.99,
    category: ["biking", "accessories"],
    weather: ["all-weather"],
    activities: ["cycling", "mountain biking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "triathlon-wetsuit-mens",
    name: "Men's Triathlon Wetsuit",
    description: "Buoyancy-enhancing, flexible wetsuit designed for open water swimming.",
    price: 299.99,
    category: ["triathlon", "swimming"],
    weather: ["cold", "mild"],
    activities: ["triathlon", "swimming"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "triathlon-wetsuit-womens",
    name: "Women's Triathlon Wetsuit",
    description: "Streamlined, hydrodynamic wetsuit for faster swim times.",
    price: 299.99,
    category: ["triathlon", "swimming"],
    weather: ["cold", "mild"],
    activities: ["triathlon", "swimming"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "triathlon-bike",
    name: "Aero Triathlon Bike",
    description: "Lightweight carbon fiber frame with aero handlebars for maximum speed.",
    price: 2999.99,
    category: ["triathlon", "biking"],
    weather: ["all-weather"],
    activities: ["triathlon", "cycling"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "clip-on-aero-bars",
    name: "Clip-On Aero Bars",
    description: "Transform your road bike into a triathlon-ready setup.",
    price: 129.99,
    category: ["triathlon", "biking"],
    weather: ["all-weather"],
    activities: ["triathlon", "cycling"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "triathlon-running-shoes",
    name: "Triathlon Running Shoes",
    description: "Elastic laces and breathable design for quick transitions.",
    price: 159.99,
    category: ["triathlon", "running"],
    weather: ["all-weather"],
    activities: ["triathlon", "running"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "triathlon-suit-mens",
    name: "Men's Triathlon Suit",
    description: "One-piece suit designed for swim, bike, and run transitions.",
    price: 149.99,
    category: ["triathlon", "clothing"],
    weather: ["warm"],
    activities: ["triathlon"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "triathlon-suit-womens",
    name: "Women's Triathlon Suit",
    description: "Quick-drying, compression-fit tri suit for endurance races.",
    price: 149.99,
    category: ["triathlon", "clothing"],
    weather: ["warm"],
    activities: ["triathlon"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "swim-goggles",
    name: "Anti-Fog Swim Goggles",
    description: "Polarized lenses for glare reduction in open water swimming.",
    price: 49.99,
    category: ["triathlon", "swimming"],
    weather: ["all-weather"],
    activities: ["triathlon", "swimming"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "swim-buoy",
    name: "Open Water Swim Buoy",
    description: "High-visibility buoy for added safety in open water training.",
    price: 39.99,
    category: ["triathlon", "swimming"],
    weather: ["all-weather"],
    activities: ["triathlon", "swimming"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "triathlon-water-bottle",
    name: "Triathlon Hydration Bottle",
    description: "Aerodynamic bottle for easy hydration on the bike leg.",
    price: 29.99,
    category: ["triathlon", "accessories"],
    weather: ["all-weather"],
    activities: ["triathlon", "cycling"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "energy-gels",
    name: "Endurance Energy Gels",
    description: "Fast-absorbing carbs and electrolytes for sustained energy.",
    price: 19.99,
    category: ["triathlon", "nutrition"],
    weather: ["all-weather"],
    activities: ["triathlon", "running", "cycling"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "race-belt",
    name: "Triathlon Race Belt",
    description: "Quick-attach race number belt with gel loops.",
    price: 19.99,
    category: ["triathlon", "accessories"],
    weather: ["all-weather"],
    activities: ["triathlon"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "transition-mat",
    name: "Triathlon Transition Mat",
    description: "Non-slip mat for fast and efficient transitions.",
    price: 39.99,
    category: ["triathlon", "accessories"],
    weather: ["all-weather"],
    activities: ["triathlon"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "foam-roller",
    name: "Deep Tissue Foam Roller",
    description: "Speeds up muscle recovery and improves flexibility.",
    price: 34.99,
    category: ["triathlon", "recovery"],
    weather: ["all-weather"],
    activities: ["triathlon", "running", "cycling"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "smart-trainer",
    name: "Indoor Smart Bike Trainer",
    description: "Realistic road feel and smart resistance control.",
    price: 899.99,
    category: ["triathlon", "biking", "training"],
    weather: ["indoor"],
    activities: ["triathlon", "cycling"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-shoes-road",
    name: "Road Running Shoes",
    description: "Lightweight, cushioned shoes designed for high-mileage road running.",
    price: 159.99,
    category: ["running", "footwear"],
    weather: ["all-weather"],
    activities: ["running", "training"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-shoes-trail",
    name: "Trail Running Shoes",
    description: "Aggressive tread and waterproof design for off-road adventures.",
    price: 149.99,
    category: ["running", "footwear"],
    weather: ["rain", "mud", "all-weather"],
    activities: ["trail running", "hiking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-race-flats",
    name: "Carbon-Plated Racing Shoes",
    description: "Ultra-light and responsive design for marathon racing.",
    price: 249.99,
    category: ["running", "footwear"],
    weather: ["all-weather"],
    activities: ["marathon", "race day"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-shirt-mens",
    name: "Men's Moisture-Wicking Running Shirt",
    description: "Breathable, sweat-resistant fabric for hot-weather runs.",
    price: 34.99,
    category: ["running", "clothing"],
    weather: ["warm", "hot"],
    activities: ["running", "training"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-shirt-womens",
    name: "Women's Lightweight Running Tank",
    description: "Racerback cut for comfort and ventilation in warm weather.",
    price: 29.99,
    category: ["running", "clothing"],
    weather: ["warm", "hot"],
    activities: ["running", "training"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-shorts-mens",
    name: "Men's 5-inch Running Shorts",
    description: "Lightweight and breathable with built-in liner.",
    price: 44.99,
    category: ["running", "clothing"],
    weather: ["warm", "hot"],
    activities: ["running", "marathon"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-shorts-womens",
    name: "Women's High-Waist Running Shorts",
    description: "Supportive, quick-dry shorts with a zip pocket.",
    price: 39.99,
    category: ["running", "clothing"],
    weather: ["warm", "hot"],
    activities: ["running", "training"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-tights-mens",
    name: "Men's Compression Running Tights",
    description: "Keeps muscles warm and reduces fatigue on long runs.",
    price: 59.99,
    category: ["running", "clothing"],
    weather: ["cold", "mild"],
    activities: ["running", "training"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-leggings-womens",
    name: "Women's Thermal Running Leggings",
    description: "Brushed fleece interior for warmth and moisture control.",
    price: 69.99,
    category: ["running", "clothing"],
    weather: ["cold"],
    activities: ["running", "training"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-windbreaker",
    name: "Ultralight Running Windbreaker",
    description: "Packable and water-resistant for breezy conditions.",
    price: 89.99,
    category: ["running", "clothing"],
    weather: ["wind", "mild"],
    activities: ["running", "training"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-rain-jacket",
    name: "Breathable Waterproof Running Jacket",
    description: "Stay dry without overheating on wet runs.",
    price: 129.99,
    category: ["running", "clothing"],
    weather: ["rain"],
    activities: ["running", "marathon"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-headlamp",
    name: "Rechargeable Running Headlamp",
    description: "Bright LED with adjustable strap for night runs.",
    price: 39.99,
    category: ["running", "accessories"],
    weather: ["all-weather"],
    activities: ["running", "trail running"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-hydration-belt",
    name: "Hydration Running Belt",
    description: "Bounce-free belt with dual water bottles and pockets.",
    price: 49.99,
    category: ["running", "accessories"],
    weather: ["warm", "hot"],
    activities: ["running", "marathon"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-smartwatch",
    name: "GPS Running Smartwatch",
    description: "Track pace, heart rate, and VO2 max with precision.",
    price: 299.99,
    category: ["running", "electronics"],
    weather: ["all-weather"],
    activities: ["running", "training"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-compression-socks",
    name: "Compression Running Socks",
    description: "Improves circulation and reduces muscle fatigue.",
    price: 29.99,
    category: ["running", "clothing"],
    weather: ["all-weather"],
    activities: ["running", "marathon"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "running-sunglasses",
    name: "Polarized Running Sunglasses",
    description: "Lightweight UV-protected lenses for bright conditions.",
    price: 79.99,
    category: ["running", "accessories"],
    weather: ["sunny"],
    activities: ["running", "trail running"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "mens-swim-trunks",
    name: "Men's Quick-Dry Swim Trunks",
    description: "Comfortable swim shorts with mesh lining and side pockets.",
    price: 34.99,
    category: ["swimming", "clothing"],
    weather: ["warm", "hot"],
    activities: ["swimming", "beach"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "womens-one-piece",
    name: "Women's Athletic One-Piece Swimsuit",
    description: "Chlorine-resistant swimsuit with moderate coverage and cross-back straps.",
    price: 49.99,
    category: ["swimming", "clothing"],
    weather: ["warm", "hot"],
    activities: ["swimming", "beach"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "womens-two-piece",
    name: "Women's Sport Bikini Set",
    description: "Athletic two-piece with racerback top and full coverage bottom.",
    price: 44.99,
    category: ["swimming", "clothing"],
    weather: ["warm", "hot"], 
    activities: ["swimming", "beach"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "board-shorts",
    name: "Long Board Shorts",
    description: "Quick-drying board shorts with UPF 50+ protection.",
    price: 39.99,
    category: ["swimming", "clothing"],
    weather: ["warm", "hot"],
    activities: ["swimming", "beach", "surfing"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "fishing-rod-carbon",
    name: "Carbon Fiber Fishing Rod",
    description: "Lightweight and durable fishing rod, perfect for freshwater and saltwater fishing.",
    price: 129.99,
    category: ["fishing", "gear"],
    weather: ["all-weather"],
    activities: ["fishing"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "fishing-reel",
    name: "High-Speed Spinning Reel",
    description: "Smooth performance with corrosion-resistant bearings, ideal for both fresh and saltwater.",
    price: 89.99,
    category: ["fishing", "gear"],
    weather: ["all-weather"],
    activities: ["fishing"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "fishing-tackle-box",
    name: "Waterproof Fishing Tackle Box",
    description: "Organized storage for lures, hooks, and fishing accessories.",
    price: 39.99,
    category: ["fishing", "storage"],
    weather: ["all-weather"],
    activities: ["fishing"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "fishing-bait-kit",
    name: "Deluxe Fishing Bait Kit",
    description: "A selection of artificial baits and lures for a variety of fish species.",
    price: 49.99,
    category: ["fishing", "gear"],
    weather: ["all-weather"],
    activities: ["fishing"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "fishing-waders",
    name: "Chest-High Fishing Waders",
    description: "Waterproof and breathable waders with reinforced knee protection.",
    price: 159.99,
    category: ["fishing", "clothing"],
    weather: ["cold", "mild"],
    activities: ["fishing"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "fishing-vest",
    name: "Multi-Pocket Fishing Vest",
    description: "Lightweight vest with multiple pockets for tackle and gear.",
    price: 79.99,
    category: ["fishing", "clothing"],
    weather: ["mild", "warm"],
    activities: ["fishing"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  }  ,
  {
    id: "softshell-vest",
    name: "Men’s Softshell Vest",
    description: "Wind and water-resistant vest with fleece lining for core warmth.",
    price: 99.99,
    category: ["clothing", "outerwear"],
    weather: ["mild", "wind"],
    activities: ["hiking", "camping"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "fleece-vest",
    name: "Women’s Fleece Vest",
    description: "Lightweight and warm vest for layering during outdoor activities.",
    price: 79.99,
    category: ["clothing", "outerwear"],
    weather: ["mild", "cold"],
    activities: ["hiking", "camping", "casual"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "athletic-tank-mens",
    name: "Men’s Performance Tank Top",
    description: "Moisture-wicking and breathable tank top for active wear.",
    price: 34.99,
    category: ["clothing"],
    weather: ["warm", "hot"],
    activities: ["hiking", "running", "gym"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "athletic-tank-womens",
    name: "Women’s Performance Tank Top",
    description: "Lightweight and sweat-resistant tank for high-intensity workouts.",
    price: 34.99,
    category: ["clothing"],
    weather: ["warm", "hot"],
    activities: ["hiking", "running", "gym"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "long-sleeve-hiking-shirt",
    name: "Long-Sleeve UPF Hiking Shirt",
    description: "Sun-protective, quick-dry shirt for long outdoor adventures.",
    price: 59.99,
    category: ["clothing", "sun-protection"],
    weather: ["warm", "mild"],
    activities: ["hiking", "camping", "fishing"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "hiking-wipes",
    name: "Biodegradable Body Wipes",
    description: "Gentle, unscented body wipes for keeping clean on multi-day hikes.",
    price: 12.99,
    category: ["hygiene", "camping"],
    weather: ["all-weather"],
    activities: ["hiking", "camping", "backpacking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "hand-sanitizer-gel",
    name: "Travel-Sized Antibacterial Gel",
    description: "Kills 99.99% of germs, compact for backpacking and outdoor use.",
    price: 4.99,
    category: ["hygiene", "safety"],
    weather: ["all-weather"],
    activities: ["hiking", "camping", "travel"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "camping-soap",
    name: "Eco-Friendly Camping Soap",
    description: "Biodegradable soap for washing dishes, hands, and even clothes.",
    price: 9.99,
    category: ["hygiene", "camping"],
    weather: ["all-weather"],
    activities: ["camping", "backpacking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "quick-dry-towel",
    name: "Quick-Dry Microfiber Towel",
    description: "Absorbent and compact, perfect for outdoor adventures.",
    price: 24.99,
    category: ["hygiene", "camping"],
    weather: ["all-weather"],
    activities: ["hiking", "camping", "swimming"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "ski-jacket-mens",
    name: "Men's Insulated Ski Jacket",
    description: "Waterproof, breathable, and insulated for warmth on the slopes.",
    price: 249.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "extreme-cold", "snow"],
    activities: ["skiing", "snowboarding"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "ski-jacket-womens",
    name: "Women's Insulated Ski Jacket",
    description: "Designed for performance and style, featuring a snow skirt and adjustable hood.",
    price: 249.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "extreme-cold", "snow"],
    activities: ["skiing", "snowboarding"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "ski-pants-mens",
    name: "Men's Waterproof Ski Pants",
    description: "Fully seam-sealed pants with reinforced knees for extra durability.",
    price: 199.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "snow"],
    activities: ["skiing", "snowboarding"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "ski-pants-womens",
    name: "Women's Waterproof Ski Pants",
    description: "Lightweight, insulated pants with snow gaiters to keep out powder.",
    price: 199.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "snow"],
    activities: ["skiing", "snowboarding"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "ski-gloves",
    name: "Insulated Ski Gloves",
    description: "Windproof, waterproof gloves with touchscreen-compatible fingertips.",
    price: 89.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "extreme-cold", "snow"],
    activities: ["skiing", "snowboarding"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "ski-goggles",
    name: "Anti-Fog Ski Goggles",
    description: "UV-protected, anti-fog lenses with wide peripheral vision.",
    price: 99.99,
    category: ["accessories", "ski", "snow"],
    weather: ["cold", "snow", "sunny"],
    activities: ["skiing", "snowboarding"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "ski-helmet",
    name: "Lightweight Ski Helmet",
    description: "Impact-resistant and breathable with an adjustable fit.",
    price: 129.99,
    category: ["safety", "ski", "snow"],
    weather: ["cold", "snow"],
    activities: ["skiing", "snowboarding"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "ski-socks",
    name: "Thermal Merino Wool Ski Socks",
    description: "Moisture-wicking and extra warm for long days in the snow.",
    price: 29.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "extreme-cold"],
    activities: ["skiing", "snowboarding"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "ski-boot-bag",
    name: "Padded Ski Boot Bag",
    description: "Durable, waterproof bag to transport ski boots and gear.",
    price: 79.99,
    category: ["bags", "ski", "travel"],
    weather: ["all-weather"],
    activities: ["skiing", "snowboarding", "travel"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "heated-gloves",
    name: "Battery-Powered Heated Gloves",
    description: "Rechargeable gloves that provide up to 8 hours of warmth.",
    price: 149.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["extreme-cold"],
    activities: ["skiing", "snowboarding", "mountaineering"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "heated-socks",
    name: "Electric Heated Ski Socks",
    description: "Adjustable temperature control keeps feet warm in freezing conditions.",
    price: 129.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["extreme-cold"],
    activities: ["skiing", "snowboarding", "hiking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "snowshoes",
    name: "Aluminum Frame Snowshoes",
    description: "Lightweight and durable for easy travel over deep snow.",
    price: 179.99,
    category: ["footwear", "winter-gear", "snow"],
    weather: ["cold", "snow"],
    activities: ["snowshoeing", "hiking"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "ski-backpack",
    name: "Ski Touring Backpack",
    description: "Hydration-compatible pack with ski-carry straps and avalanche tool storage.",
    price: 149.99,
    category: ["bags", "ski", "safety"],
    weather: ["cold", "snow"],
    activities: ["skiing", "snowboarding", "mountaineering"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "avalanche-beacon",
    name: "Avalanche Rescue Beacon",
    description: "Essential for backcountry safety, fast and accurate location tracking.",
    price: 299.99,
    category: ["safety", "ski"],
    weather: ["cold", "snow"],
    activities: ["backcountry skiing", "snowboarding", "mountaineering"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  },
  {
    id: "balaclava",
    name: "Thermal Fleece Balaclava",
    description: "Full face protection against wind and extreme cold.",
    price: 24.99,
    category: ["clothing", "winter-gear", "ski"],
    weather: ["cold", "wind", "snow"],
    activities: ["skiing", "snowboarding", "mountaineering"],
    image: "https://adexusa.com/wp-content/uploads/2022/11/Floor-Square-en-rWt2QxfUBxF2UvRz.jpg",
  }  
]
